### PR TITLE
v14.1.2

### PR DESCRIPTION
**Pull request by jdecked**
Fixes twitter#563.

### CODE REVIEW

**Comment by jeremynoesen** [comment]
These emojis look normal finally! Thanks for this!

**Comment by Makefile-dot-in** [comment]
i liked the previous design for the normal pleading emoji better tbh (i agree that face holding back tears looked pretty cursed though). in my subjective opinion, it also feels like these don't really fit in well with the rest of the emoji – to me it almost looks lighter, even though it isn't, and – it's also just iconic; for me, it is one of the most identifiable aspects of the twemoji design. if this repository wants to become the new main twemoji fork, as it seems it does, i think it should preserve one of its most iconic designs instead of going with the same design every other emoji set uses.

my suggestion would be returning to the previous design and either picking a new matching design for the holding back tears emoji, potentially from the issue linked.

**Comment by VoxelDoesCode** [comment]
Yeah, looking at the new emoji next to the other ones, it feels out of place. The black used for the eyes stands out too much compared to the nice orange shade used for the rest of the face. For the old pleading_face, it worked because the pupils were also the orange shade, and left plenty of room for the eye whites. My suggestion would be to clean up the eye shapes used in the old versions, and maybe try and rework holding_back_tears into some midpoint between the old and new one? Not sure how to describe it properly.

**Comment by winterClover** [comment]
on the topic of eye color, the emojis for 😜🤪😳🫣 uses black for pupils, but yet 🙄 uses brown. for consistency sake why not make all pupils brown like the rest of the emojis?

**Comment by 66minmin** [comment]
> i liked the previous design for the normal pleading emoji better tbh (i agree that face holding back tears looked pretty cursed though).

this. the previous normal pleading emoji was absolutely iconic. the face holding back tears was pretty bad, and this updated design is definitely much much better.
i sincerely hope you guys revert the normal pleading emoji and try to find an updated design the face holding back tears that can more closely match the pleading emoji.

**Comment by Eirenliel** [comment]
cowards, brign 🥺 back

**Comment by april83c** [comment]
this is a hate crime against bottoms

**Pull request merged**
