### PR TITLE
Change the Antartica flag emoji

### PR DESCRIPTION
**Pull request by leap0x7b**
Use the "True South" Antartica flag instead of Graham Bartram's flag. The "True South" flag has been regarded as the "official" flag of Antartica by many national Antarctic programs and non-profits. Don't know why emoji makers don't change it to this flag though.

### CODE REVIEW

**Comment by Xstoudi** [comment]
I think the True South flag would be better than the Graham Bartram, but as described in the [flag spec](https://www.truesouthflag.com/design) there should be an inside margin on the bottom side, as there is one on the top side.

**Comment by leap0x7b** [comment]
Yeah it's actually an error in my part, fixing that later.

**Comment by 12Me21** [comment]
(for anyone wondering: this is getting attention because of a youtube video by CGP Gray)

**Comment by leap0x7b** [comment]
who tf disliked this

**Comment by jdecked** [comment]
Thanks for your submission! We're not going to merge this right now because we'd be an outlier with all other major emoji sets. Having reasonable amounts of design parity across emoji sets helps avoid misunderstandings when users are using emoji to communicate. If/when major keyboard vendors plan to change their representation of the flag of Antarctica, we'd be willing to revisit this.

**Pull request closed without merging**
