### PR TITLE
fix skull png

### PR DESCRIPTION
**Pull request by advaith1**
Hi, I'm Advaith from Discord. I got a report from a user that the skull emoji appears differently on Android vs desktop, particularly the eyes are different shapes. It seems to be because the [PNG image](https://github.com/jdecked/twemoji/blob/main/assets/72x72/1f480.png) is different from the [SVG image](https://github.com/jdecked/twemoji/blob/main/assets/svg/1f480.svg). On desktop we use the SVGs but on Android we use the PNGs.

| PNG | SVG |
| --- | --- |
| image | image |

I used rsvg-convert to convert the skull's SVG to PNG so they are consistent now. However, this seems to have increased the file size significantly - is there a preferred way of optimizing the PNG?

### CODE REVIEW

**Comment by jdecked** [comment]
Hi @advaith1, thanks for reporting this! Usually we run the PNGs through ImageOptim at the highest compression, then confirm the compressed & original PNGs visually match. Happy to merge this once you've done that, and I assume you'll need a patch version to be published on NPM too?

**Comment by advaith1** [comment]
Thanks, compressed!

re npm, it looks like the png files are not published to npm? We pull them from our GitHub fork.

**Comment by jdecked** [comment]
> re npm, it looks like the png files are not published to npm? We pull them from our GitHub fork.

They aren't, but they're referenced in the code through a CDN that pulls from GitHub tags. If you just pull the images alone from your own fork/don't use the referencing code, it should be fine (unless you also rely on the tags somehow). I'll merge this now (from mobile).

**Review by jdecked — APPROVED** [review]

**Comment by 12Me21** [comment]
Actually, the png was correct, it's the svg that is wrong here.
https://github.com/jdecked/twemoji/issues/34
Several emojis have shapes which were incorrectly replaced with circles/ellipses by an "optimization" many years ago
(the reason the png became desynchronized in the first place was because the svg was mistakenly changed, during an operation which supposed to reduce its filesize without changing the appearance, so they didn't re-render the pngs)

**Pull request merged**
