### PR TITLE
Add emoji 15-15.1

### PR DESCRIPTION
**Pull request by Sayhone721**
Beware that not all of Emoji 15 and 15.1 is there. I wanted to continue the development of Twemoji. I hate how Elon Musk decided to abandon the project.

### CODE REVIEW

**Comment by JeDaYoshi** [comment]
This will likely get closed because of https://github.com/jdecked/twemoji/issues/8#issuecomment-1610361826. This cannot be merged.

**Comment by Sayhone721** [comment]
@JeDaYoshi, I know I closed it, but I thought she was talking about the ones that are used on the Twitter website.

**Comment by Felting** [comment]
> @JeDaYoshi, I know I closed it, but I thought she was talking about the ones that are used on the Twitter website.

Where are these images sourced from? The ones from twitter aren’t allowed because they aren’t licensed.

**Comment by Sayhone721** [comment]
They're sourced from the original Twitter emojis, I just edited the existing ones.

**Comment by JeDaYoshi** [comment]
That still counts as copyright infringement, unless they open-source them under the Twemoji project.

**Comment by dbrgn** [comment]
@JeDaYoshi the original artwork that was part of Twemoji was licensed under the "CC BY 4.0" license: https://github.com/jdecked/twemoji/blob/main/LICENSE-GRAPHICS This license allows derivative works.

From what I can tell, the emoji added by @Sayhone721 are neither copied from the Twitter website, nor are they close copies of the newly added Twitter emoji. As such, I don't see how this is a copyright infringement?

**Comment by JeDaYoshi** [comment]
@dbrgn Please correct me if I'm wrong, but as far as I've understood it, the images were sourced from Twitter's website, which since they've not been officially released under the Twemoji project and have only been available from there, we should take them as "not licensed", being a gray area of probably rights reserved (or not).

Yes, afterwards the emojis were edited when the PR was submitted, but wouldn't that still be an issue due to the source they came from? It's not like they were created from scratch using the Twitter emoji's design as an inspiration.

**Comment by JeDaYoshi** [comment]
I'm pretty much following @jdecked's comment as of why prior PRs to add the new emojis were not merged - they can't be sourced from Twitter at all. I'm counting "derivate works based on Twitter's SVG files" on this, which is what I originally thought when commenting on this PR, and @Sayhone721 confirmed in an earlier comment.

**Pull request closed without merging**
