### PR TITLE
Switch to pistol

### PR DESCRIPTION
**Pull request by VoxelPrismatic**

### CODE REVIEW

**Comment by jdecked** [comment]
1. This image is neither in the public domain nor your own creation
2. Changing the water pistol back to display as a gun would put us out of alignment with every other major emoji vendor

**Comment by VoxelPrismatic** [comment]
This is Twemoji. If it isn't, then rename the project or add a warning to the readme saying that it has nothing to do with X, and any emojis lifted from X will be ignored.

**Comment by jdecked** [comment]
We literally cannot lift emoji off X.com due to copyright law. The emoji we have that also appear on X were previously published under a permissive license on the twitter/twemoji GitHub repo. Further emoji created for use on X haven't been similarly published, so we don't have the right to use them.

**Comment by iMonZ** [comment]
> r emoji cre

I would say this makes this project and repo completly useless...

**Comment by actuallyaridan** [comment]
No, this is a continuation of Twemoji. This is not a way to get emojis from X for free because that’s quite literally illegal because the emojis that are on X today are not free to use. Also, the gun emoji does **not** comply with emoji standards. 

You should be asking X to follow emoji standards, not Twemoji to break them because one gun-obsessed billionaire who influenced the US election so he could do a special salute on TV did so.

This is Twitter Emoji. Not X Emoji.

**Comment by VoxelPrismatic** [comment]
Are you high?

**Comment by VoxelPrismatic** [comment]
Just because something may be "seen" as the new standard doesn't mean it is.

> I’d treat these as glyph changes within fonts.

https://unicode.org/mail-arch/unicode-ml/y2018-m05/0071.html

**Comment by VoxelPrismatic** [comment]
> It’s a de facto standard

No, it isn't. The pistol is the standard. 

> Emojis are a language, it needs to be consistent cross platform

Yes, so how about we all abide by the standard set by Unicode instead of whatever semantic nonsense that whatever you and your standards-breaking friends agreed upon.

**Comment by Nerixyz** [comment]
> Yes, so how about we all abide by the standard set by Unicode instead of whatever semantic nonsense that whatever you and your standards-breaking friends agreed upon.

Vendors are free to choose their colorful presentation of the glyphs (see https://unicode.org/mail-arch/unicode-ml/y2018-m05/0073.html). Depicting U+1F52B as a firearm or as a water gun are both fine.
Now if a vendor wants to ensure semantic compatibility with other major vendors, it's their right to do so and not a violation of a standard.

**Pull request closed without merging**
