### PR TITLE
Add Jellyfish emoji (U+1FABC)

### PR DESCRIPTION
**Pull request by treuks**
Chips off a small bit off of #8

Hello there to the wonderful people behind twemoji, really like the emojis, wanted to contribute myself, here's a jellyfish emoji.
It's basically my first time doing minimalistic vector art like this, so I would appreciate some helpful feedback

Frame 5

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
It's kinda shiny and no other emoji has shine/reflection. I'm not sure if totally fits the theme.

**Comment by treuks** [comment]
image

**Comment by treuks** [comment]
Actually, I think the "shine" might be too bright. I'll fix it

**Comment by treuks** [comment]
Here's what it looks like now
Frame 5 (4)

**Pull request closed without merging**
