### PR TITLE
markdown fixes, html tweaks, and two emoji consistency fixes

### LINKED ISSUE #70: Blue heart (1f499) is different shade than other blue emojis such as blue square, circle, etc.
_Copied (with modified links) from https://github.com/twitter/twemoji/issues/629_

The [blue heart SVG, 1f499](https://github.com/jdecked/twemoji/blob/master/assets/svg/1f499.svg) uses the hex color `#5DADEC`, while the other blue emojis, e.g. [blue circle, 1f535](https://github.com/jdecked/twemoji/blob/master/assets/svg/1f535.svg), [blue square, 1f7e6](https://github.com/jdecked/twemoji/blob/master/assets/svg/1f7e6.svg), etc. use the hex color `#55ACEE`.

**To Reproduce**
Check the text/source of the [blue heart SVG](https://github.com/jdecked/twemoji/blob/master/assets/svg/1f499.svg) against that of the [blue circle](https://github.com/jdecked/twemoji/blob/master/assets/svg/1f535.svg) and [blue square](https://github.com/jdecked/twemoji/blob/master/assets/svg/1f7e6.svg) SVGs, and compare the value in the `fill` attribute.

**Expected behavior**
The blue heart should be the same color as the other blue- emojis.

I also checked the large blue diamond and small blue diamond SVGs, which both used `#55ACEE`.

### PR DESCRIPTION
**Pull request by SpiritAxolotl**
Most notable non-emoji changes:
- Markdown formatting
  - Changed all emphases with asterisks (\*text\*) to underscores (\_text\_)
  - Removed slashes from the end of links
  - Trimmed the whitespace a bit in code snippets
- Replaced all instances of `master` with `main`
- Fixed incorrectly hyperlinked things
- Clarified a few commands
  - `yarn prepublish` isn't a command, but `yarn prepublishOnly` _was_
  - `git clone -b master {repo}` was shortened to `git clone {repo}` (again, `master` doesn't exist)
- Changed a few `var`s to `let`s
- Cleaned up the markdown in FOLDERS.md
  - Added more whitespace to make most of the columns align better in the editor
  - Put the Top level, Second, and Files column contents in code snippets (fixes the incorrect markdown emphasis)
- Re-added the correct emojis after being changed in commit [65f4a5d](https://github.com/jdecked/twemoji/commit/65f4a5da05f347cfe37779a586d4480a4400a28d#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R43)

Emoji changes:
- The eyebrows of `:imp:` (`\u1f47f`) are now consistent with that of `:smiling-imp:` (`\u1f608`)
- The color of the blue heart is now consistent with other blue objects (resolves #70)

Running `yarn prepublishOnly` didn't prompt me to change the version number, otherwise I would have made it `15.2.1`

Last thing: I had to install jq with brew in order to even use that yarn command, so should I put add it as an extra step for macOS users in CONTRIBUTING.md?

### CODE REVIEW

**Comment by SpiritAxolotl** [comment]
gonna make this up-to-date soon

**Comment by SpiritAxolotl** [comment]
I also realize that it might be better for me to separate this pr into two prs, one for the general fixes and another for the emoji tweaks. Should I do that?

**Comment by SpiritAxolotl** [comment]
activity going well it seems

**Comment by jdecked** [comment]
> activity going well it seems

I understand that having a PR sit for a while is frustrating. Committing one mega-PR that changes 47 files with a combo of explained, unexplained, and linting preference changes is not an efficient way to contribute to OSS (or, really, to most projects used by many people). Generally PRs like these go to the bottom of most OSS maintainers' to-do lists because reviewing them takes much more coaching/feedback than the average maintainer has time for, even if the changes themselves aren't complicated: you're effectively handing the maintainer a pile of coloured bricks and asking them to sort the bricks for you before adding them to the building. Some OSS projects have the bandwidth to coach people into making higher efficiency contributions, but not all (or even most).

Twemoji typically follows a once a year release cadence in line with Unicode – typically with a few patches in between. We often batch the "please redesign XYZ emoji" issue requests into one patch or (less frequently) the next minor/major release. Patches come out when we have time for non-critical issues: unlike some other OSS projects, Twemoji isn't anyone's day job.

Now that I've explained this to you, hopefully you realize the sarcasm wasn't necessary.

**Comment by SpiritAxolotl** [comment]
I do wish there was an acknowledgement of this pr but it wasn't a reason for me to be sassy about it. sorry about that.

I'll close this pr and split it into one for markdown and one for the actual emoji changes at some point in the future. I don't understand why the new emojis were written to by the github action in commit [94c7591](https://github.com/jdecked/twemoji/pull/74/commits/94c7591a00c4cacbe9e77900a48a002d28c5593a) when I pulled from the upstream. hopefully that won't happen next time when I fork it from the upstream originally.

again, really sorry for the sarcasm, and thank you for doing god's work with this project.

**Pull request closed without merging**
